version: 2.1

orbs:
  node: circleci/node@5.1.0
  slack: circleci/slack@4.12.5

executors:
  playwright-executor:
    docker:
      - image: mcr.microsoft.com/playwright:v1.40.0-focal
    working_directory: ~/project
    resource_class: medium

jobs:
  run-automation-tests:
    executor: playwright-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Playwright Browsers
          command: |
            npx playwright install chromium
            npx playwright install-deps chromium
      - run:
          name: Run Playwright Tests
          command: |
            npm run test || true
            if [ -d "allure-results" ] && [ "$(ls -A allure-results)" ]; then
              npx allure generate allure-results --clean -o allure-report
            else
              echo "No allure results found"
            fi
          environment:
            CI: true
          no_output_timeout: 15m
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: allure-report
          destination: allure-report
      - store_artifacts:
          path: playwright-report
          destination: playwright-report
      - store_artifacts:
          path: test-results
          destination: test-results
      - slack/notify:
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "✅ *Automation Tests Passed!*\n\n*Project:* $CIRCLE_PROJECT_REPONAME\n*Branch:* $CIRCLE_BRANCH\n*Build:* $CIRCLE_BUILD_NUM"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Allure Report"
                      },
                      "url": "$CIRCLE_BUILD_URL/artifacts/0/allure-report/index.html"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Build"
                      },
                      "url": "$CIRCLE_BUILD_URL"
                    }
                  ]
                }
              ]
            }
      - slack/notify:
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "❌ *Automation Tests Failed!*\n\n*Project:* $CIRCLE_PROJECT_REPONAME\n*Branch:* $CIRCLE_BRANCH\n*Build:* $CIRCLE_BUILD_NUM"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Allure Report"
                      },
                      "url": "$CIRCLE_BUILD_URL/artifacts/0/allure-report/index.html"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Failed Tests"
                      },
                      "url": "$CIRCLE_BUILD_URL/artifacts/0/test-results/index.html"
                    }
                  ]
                }
              ]
            }

workflows:
  version: 2
  automation-on-merge:
    jobs:
      - run-automation-tests:
          filters:
            branches:
              only:
                - storagely-automation
          context: slack-secrets
